[book]
authors = ["ramdevcm"]
language = "en"
multilingual = false
src = "src"
title = "myprep"

[output.html]
mathjax-support = true
site-url = "/src/"
git-repository-url = "https://github.com/ramdevcm/mypreps"
